### ISSUE TITLE
Running the contributed command:'findJump.activate' failed when using vscodevim

### ISSUE THREAD

**Issue by lcsdms** [msafi/xvsc#11]
Hi ! I'm trying to use the extension, but when I mapped the keybinding, or when I try to run the command directly from the command palette (CTRL+SHIFT+P), I get the following error:

> Running the contributed command:'findJump.activate' failed.

Additional Info:
Running VSCode version 1.23.0 on X64
Find-Jump 1.2.4

This is my keybinding.json
```
[
{ "key": "ctrl+;","command": "findJump.activate", "when": "editorTextFocus" }
]
```

Am I doing something wrong ? thanks!

**Comment by lcsdms** [comment]
Thanks for your feedback!
After some testing I found out this problem happens when using this extension together with vscodevim.

Tried mapping the ctrl+; to the exclusion of the vim plugin, to be handled only by the vscode, but it seems like a incompatibility problem, since running from the command pallete also has erros.

Here's the console log:

When I run using the ctrl+; keybinding:
```
[Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.
browser.ts:139 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
```

When I run using the command pallete I get the same error but with different alert from the console.

After disabling code vim the extension works as expected.

I know there's a similar use with easymotion that is avaiable in vim but I like the way find-jump works better, as I already use it on jetbrains IDE.

**Comment by karambaq** [comment]
So, is there a way to use it with vscodevim?

**Comment by lcsdms** [comment]
Hi @karambaq! Unfortunately, I was not able to make it work together with vscodevim :(

**Comment by singuerinc** [comment]
@lcsdms any news on this one? I would like to use Find-Jump + amVim.

**Comment by frithrah** [comment]
Find-Jump is the best implementation of AceJump I've ever used. Great work. I just wish it worked with amVim. Can you see any way of doing this?

**Comment by singuerinc** [comment]
Debugging the extension I figured out that the problem is that both extensions register the same command `"type"` and that's why it's failing.

amVim
https://github.com/aioutecism/amVim-for-VSCode/blob/623f8868fdf2c1054dcd6fc3a91612d3301f5924/src/Dispatcher.ts#L35

findJump
https://github.com/msafi/xvsc/blob/master/findJump/src/inlineInput.ts#L23

@msafi I don't have experience building extensions so I don't know how to fix that, but maybe this gives you any idea on how to deal with this issue.

And the error stack:

```
"Error: command 'type' already exists
at d.registerCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:436:447)
at Object.registerCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:638:335)
at new InlineInput (/Users/singuerinc/src/code/singuerinc/xvsc/findJump/out/src/inlineInput.js:34:54)
at constructor.activate (/Users/singuerinc/src/code/singuerinc/xvsc/findJump/out/src/findJump.js:20:32)
at t.createApiFactory.C.registerTextEditorCommand.fe.registerCommand.i.edit.e (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:638:500)
at p.edit (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:410:52)
at t.createApiFactory.C.registerTextEditorCommand.fe.registerCommand.r (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:638:474)
at d._executeContributedCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:437:409)
at d.$executeContributedCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:437:783)
at h._doInvokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:564:459)
at h._invokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:564:151)
at h._receiveRequest (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:562:825)
at h._receiveOneMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:561:707)
at define.constructor._protocol.onMessage.e (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:559:990)
at e (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:34:638)
at u.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:38:806)
at s (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:154:754)
at Socket.define.constructor._socketDataListener.e (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:154:960)
at Socket.emit (events.js:182:13)
at addChunk (_stream_readable.js:279:12)
at readableAddChunk (_stream_readable.js:264:11)
at Socket.Readable.push (_stream_readable.js:219:10)
at Pipe.onread (net.js:636:20)"
```

**Comment by singuerinc** [comment]
For those looking for an alternative (until this issue is resolved), I found that (although it's not good as find-jump) https://marketplace.visualstudio.com/items?itemName=lucax88x.codeacejumper works with amVim.

**Comment by fklement** [comment]
I'm having the same problem!!!  
Really would appreciate if I could use vim together with find-jump.  
I love find-jump! ❤️

**Comment by xieyabos** [comment]
me too ,really sad

**Comment by XaydBayeck** [comment]
I'm using the neovim plugin, and I'm having the same problem.
It seems that all vim-like plugins have the same problem.
```
[2020-05-10 17:34:40.717] [exthost] [info] ExtensionService#_doActivateExtension mksafi.find-jump {"startup":false,"extensionId":{"value":"mksafi.find-jump","_lower":"mksafi.find-jump"},"activationEvent":"onCommand:findJump.activate"}
[2020-05-10 17:34:40.717] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/sid/.vscode-oss/extensions/mksafi.find-jump-1.2.4/out/src/extension
[2020-05-10 17:34:40.733] [exthost] [error] Error: command 'type' already exists
	at e.registerCommand (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:590:958)
	at Object.registerCommand (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:860:29)
	at new InlineInput (/home/sid/.vscode-oss/extensions/mksafi.find-jump-1.2.4/out/src/inlineInput.js:32:54)
	at FindJump.activate (/home/sid/.vscode-oss/extensions/mksafi.find-jump-1.2.4/out/src/findJump.js:20:32)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:860:181
	at t.ExtHostTextEditor.edit (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:552:588)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:860:170
	at e._executeContributedCommand (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:592:220)
	at e.$executeContributedCommand (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:592:595)
	at e._doInvokeHandler (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:752:683)
	at e._invokeHandler (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:752:375)
	at e._receiveRequest (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:751:14)
	at e._receiveOneMessage (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:749:832)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:748:34
	at e.fire (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48:497)
	at v.fire (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:206:615)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:919:744
	at e.fire (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48:497)
	at v.fire (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:206:615)
	at t.PersistentProtocol._receiveMessage (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:211:17)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:208:155
	at e.fire (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48:497)
	at p.acceptChunk (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:204:129)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:203:483
	at Socket.t (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:212:565)
	at Socket.emit (events.js:203:13)
	at Socket.EventEmitter.emit (domain.js:476:20)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17) findJump.activate
```
