### ISSUE TITLE
Running activation command failed

### ISSUE THREAD

**Issue by ColCh** [msafi/xvsc#15]
`Running the contributed command:'findJump.activate' failed.`

```
[2018-10-19 18:38:51.500] [exthost] [error] Error: command 'type' already exists
	at e.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:451:595)
	at Object.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:603:111)
	at new InlineInput (/Users/colch/.vscode/extensions/mksafi.find-jump-1.2.4/out/src/inlineInput.js:32:54)
	at FindJump.activate (/Users/colch/.vscode/extensions/mksafi.find-jump-1.2.4/out/src/findJump.js:20:32)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:603:359
	at e.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:439:499)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:603:325
	at e._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:452:706)
	at e.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:453:212)
	at t._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:640:888)
	at t._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:640:554)
	at t._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:639:126)
	at t._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:638:59)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:635:926
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:138
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:99:496)
	at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:154:213)
	at Socket._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:154:432)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20) findJump.activate

```

**Comment by rjhilgefort** [comment]
I know this is an old thread, but I'm seeing this error as well. I'm coming from Vim and miss this functionality. Is there a workaround to this issue or another package to try? Thanks!

**Comment by ColCh** [comment]
Removal of this extension helped me https://marketplace.visualstudio.com/items?itemName=mksafi.find-jump

**Comment by rjhilgefort** [comment]
Isn't that this extension?

**Comment by ColCh** [comment]
This seems to be a bundle of extensions, not a single one. I may be wrong though
